from config import settings

EXPIRY_DATE = 60 * 60 * 24 * 7
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24

ALGORITHM = settings.ALGORITHM
SECRET_KEY = settings.SECRET_KEY
GOOGLE_CLIENT_ID = settings.GOOGLE_CLIENT_ID
